# Enable sponsor buttons (optional)
github: []
open_collective: 
patreon: 
custom: ["https://buymeacoffee.com/vibheksoni", "https://github.com/vibheksoni/stealth-browser-mcp#-support-this-project"]


